language: python
python:
 - "2.7"
install: pip install -r requirements.txt
script: sh run_travis.sh

script:
 -test.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
